# Generated by Django 6.0 on 2026-02-05 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signature', models.TextField(blank=True)),
                ('signer_pubkey', models.TextField(blank=True)),
                ('signer_privkey_encrypted', models.TextField(blank=True, help_text='Clé privée chiffrée (simulée)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='Ce contenu est chiffré en base de données (AES-256).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='documents.department')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('classification_level', models.CharField(choices=[('PUBLIC', 'Public (Tout le monde)'), ('INTERNAL', 'Interne (Département entier)'), ('SECRET', 'Secret (Staff département uniquement)'), ('PERSONAL', 'Personnel (Destinataire unique)')], default='INTERNAL', max_length=20)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('status', models.CharField(default='approved', max_length=20)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('integrity_verified_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.department')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_department_staff', models.BooleanField(default=False, help_text='Est responsable/staff du département')),
                ('is_oauth_user', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=10)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLogAccessTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('view', 'Viewed audit log'), ('export', 'Exported audit log'), ('search', 'Searched audit log'), ('verify_integrity', 'Verified log integrity')], max_length=50)),
                ('filters_applied', models.TextField(blank=True, help_text='JSON with applied filters')),
                ('records_accessed', models.IntegerField(default=0)),
                ('export_format', models.CharField(blank=True, choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['user', 'accessed_at'], name='documents_a_user_id_ead916_idx'), models.Index(fields=['action', 'accessed_at'], name='documents_a_action_c8e94e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestrictedAuditAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('view', 'Can view audit logs'), ('export', 'Can export audit logs'), ('verify', 'Can verify audit log integrity'), ('manage', 'Can manage audit log access')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_access_grants_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'access_level'], name='documents_r_user_id_c14b12_idx'), models.Index(fields=['expires_at'], name='documents_r_expires_ce083d_idx')],
                'unique_together': {('user', 'access_level')},
            },
        ),
        migrations.CreateModel(
            name='WORMAuditLog',
            fields=[
                ('entry_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('view', 'Document View'), ('download', 'Document Download'), ('upload', 'Document Upload'), ('modify', 'Document Modify'), ('delete', 'Document Delete'), ('share', 'Document Share'), ('access_denied', 'Access Denied'), ('mfa_verify', 'MFA Verification'), ('key_rotation', 'Key Rotation'), ('quarantine_approve', 'Quarantine Approve'), ('quarantine_reject', 'Quarantine Reject')], db_index=True, editable=False, max_length=50)),
                ('ip_address', models.GenericIPAddressField(editable=False)),
                ('user_agent', models.CharField(blank=True, editable=False, max_length=500)),
                ('success', models.BooleanField(db_index=True, default=True, editable=False)),
                ('details', models.TextField(blank=True, editable=False)),
                ('document_id', models.BigIntegerField(blank=True, db_index=True, editable=False, null=True)),
                ('document_hash', models.CharField(blank=True, editable=False, help_text='SHA-256 of document at time of access', max_length=64)),
                ('previous_entry_hash', models.CharField(blank=True, editable=False, help_text='Hash of previous log entry (empty for first)', max_length=64)),
                ('entry_hash', models.CharField(db_index=True, editable=False, help_text='SHA-256 hash of this entry (immutable)', max_length=64, unique=True)),
                ('classification_level', models.IntegerField(blank=True, choices=[(1, 'Public'), (2, 'Internal'), (3, 'Confidential'), (4, 'Secret'), (5, 'Top Secret')], editable=False, null=True)),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': [('view_audit_log', 'Can view audit log'), ('export_audit_log', 'Can export audit log'), ('verify_audit_integrity', 'Can verify audit log integrity')],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='documents_w_user_id_c1e182_idx'), models.Index(fields=['action', 'timestamp'], name='documents_w_action_1de448_idx'), models.Index(fields=['ip_address', 'timestamp'], name='documents_w_ip_addr_a3146e_idx'), models.Index(fields=['document_id', 'timestamp'], name='documents_w_documen_fc3552_idx'), models.Index(fields=['success', 'timestamp'], name='documents_w_success_390591_idx')],
            },
        ),
    ]
